# Generated by Django 5.2.5 on 2025-11-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
