# Generated by Django 5.2.5 on 2025-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('Free', 'Free'), ('Bronze', 'Bronze Supporter'), ('Silver', 'Silver Supporter'), ('Gold', 'Gold Supporter')], default='Free', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
