# Generated by Django 5.2.5 on 2025-11-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0010_userprofile_tier_alter_book_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
