# Generated by Django 5.2.5 on 2025-11-11 21:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0011_book_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='ExclusiveBookMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_tiers', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Silver+', 'Silver+'), ('GoldOnly', 'Gold only')], max_length=10)),
                ('views_bronze', models.PositiveIntegerField(default=0)),
                ('views_silver', models.PositiveIntegerField(default=0)),
                ('views_gold', models.PositiveIntegerField(default=0)),
                ('favorited_bronze', models.PositiveIntegerField(default=0)),
                ('favorited_silver', models.PositiveIntegerField(default=0)),
                ('favorited_gold', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_meta', to='bookMng.book')),
            ],
        ),
    ]
