# Generated by Django 5.2.5 on 2025-11-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0012_userprofile_balance_exclusivebookmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
